// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oneof.proto

package oneof

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	// Types that are valid to be assigned to Result:
	//	*User_Ok
	//	*User_Err
	Result               isUser_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_oneof_d7658893f9b2dff8, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

type isUser_Result interface {
	isUser_Result()
}

type User_Ok struct {
	Ok string `protobuf:"bytes,1,opt,name=Ok,oneof"`
}
type User_Err struct {
	Err string `protobuf:"bytes,2,opt,name=Err,oneof"`
}

func (*User_Ok) isUser_Result()  {}
func (*User_Err) isUser_Result() {}

func (m *User) GetResult() isUser_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *User) GetOk() string {
	if x, ok := m.GetResult().(*User_Ok); ok {
		return x.Ok
	}
	return ""
}

func (m *User) GetErr() string {
	if x, ok := m.GetResult().(*User_Err); ok {
		return x.Err
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*User) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _User_OneofMarshaler, _User_OneofUnmarshaler, _User_OneofSizer, []interface{}{
		(*User_Ok)(nil),
		(*User_Err)(nil),
	}
}

func _User_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*User)
	// Result
	switch x := m.Result.(type) {
	case *User_Ok:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Ok)
	case *User_Err:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Err)
	case nil:
	default:
		return fmt.Errorf("User.Result has unexpected type %T", x)
	}
	return nil
}

func _User_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*User)
	switch tag {
	case 1: // Result.Ok
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &User_Ok{x}
		return true, err
	case 2: // Result.Err
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &User_Err{x}
		return true, err
	default:
		return false, nil
	}
}

func _User_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*User)
	// Result
	switch x := m.Result.(type) {
	case *User_Ok:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Ok)))
		n += len(x.Ok)
	case *User_Err:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Err)))
		n += len(x.Err)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*User)(nil), "oneof.User")
}

func init() { proto.RegisterFile("oneof.proto", fileDescriptor_oneof_d7658893f9b2dff8) }

var fileDescriptor_oneof_d7658893f9b2dff8 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcf, 0x4b, 0xcd,
	0x4f, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xcc, 0xb8, 0x58, 0x42,
	0x8b, 0x53, 0x8b, 0x84, 0x04, 0xb8, 0x98, 0xfc, 0xb3, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x3d,
	0x18, 0x82, 0x98, 0xfc, 0xb3, 0x85, 0x84, 0xb8, 0x98, 0x5d, 0x8b, 0x8a, 0x24, 0x98, 0xa0, 0x42,
	0x20, 0x8e, 0x13, 0x07, 0x17, 0x5b, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x49, 0x12, 0x1b, 0xd8, 0x14,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x79, 0x9d, 0xcf, 0x54, 0x00, 0x00, 0x00,
}
