[package]
name = "rust-protobuf-example"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]

[dependencies]
protobuf = { version = "~2.0", features = ["with-bytes"] }

[build-dependencies]
protoc-rust = "2.0.*"