// Code generated by protoc-gen-go. DO NOT EDIT.
// source: map.proto

package _map

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Name2Age             map[string]int32 `protobuf:"bytes,1,rep,name=Name2Age" json:"Name2Age,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_634de638f0e965af, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName2Age() map[string]int32 {
	if m != nil {
		return m.Name2Age
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "map.User")
	proto.RegisterMapType((map[string]int32)(nil), "map.User.Name2AgeEntry")
}

func init() { proto.RegisterFile("map.proto", fileDescriptor_map_634de638f0e965af) }

var fileDescriptor_map_634de638f0e965af = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4d, 0x2c, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4d, 0x2c, 0x50, 0xaa, 0xe0, 0x62, 0x09, 0x2d,
	0x4e, 0x2d, 0x12, 0x32, 0xe6, 0xe2, 0xf0, 0x4b, 0xcc, 0x4d, 0x35, 0x72, 0x4c, 0x4f, 0x95, 0x60,
	0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd7, 0x03, 0x29, 0x05, 0x49, 0xea, 0xc1, 0x64, 0x5c, 0xf3,
	0x4a, 0x8a, 0x2a, 0x83, 0xe0, 0x0a, 0xa5, 0xac, 0xb9, 0x78, 0x51, 0xa4, 0x84, 0x04, 0xb8, 0x98,
	0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6,
	0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x08, 0xc7, 0x8a, 0xc9,
	0x82, 0x31, 0x89, 0x0d, 0xec, 0x0a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0xef, 0x4d,
	0x62, 0x92, 0x00, 0x00, 0x00,
}
